[package]
name = "orderbook-proto"
version = "0.1.3"
edition = "2024"
description = "protobuf definations for grpc-trading-server"
license = "MIT"

[dependencies]
tonic = "0.14.3"
prost = "0.14.3"
tonic-prost = "0.14.3"
clob-engine = "0.3.2"

[build-dependencies]
tonic-prost-build = "0.14.3"
